CREATE TABLE IF NOT EXISTS business_printers (
    id VARCHAR(64) PRIMARY KEY,
    owner VARCHAR(50) NOT NULL,
    coords JSON NOT NULL,
    heading FLOAT NOT NULL DEFAULT 0,
    image_url TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
